server:
  port: 9090
spring:
  application:
    name: RATING-SERVICE
  config:
    import: optional:configserver:http://localhost:8086
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
    driver-class-name: ${datasource.driver-class-name}
  jpa:
    hibernate:
      ddl-auto: ${hibernate.ddl.auto}
    properties:
      hibernate:
        dialect: ${hibernate.dialect}



